# Generated by Django 4.1.4 on 2023-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("exchange", models.CharField(blank=True, max_length=120, null=True)),
                ("sector", models.CharField(blank=True, max_length=120, null=True)),
                ("industry", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("dividend_yield", models.FloatField(blank=True, null=True)),
                (
                    "analyst_recom",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "earning_date",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("avg_volume", models.FloatField(blank=True, null=True)),
                ("relative_volume", models.FloatField(blank=True, null=True)),
                ("current_volume", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("ipo_date", models.CharField(blank=True, max_length=120, null=True)),
                ("float", models.FloatField(blank=True, null=True)),
                ("outstanding_shares", models.FloatField(blank=True, null=True)),
                ("pe", models.FloatField(blank=True, null=True)),
                ("forward_pe", models.FloatField(blank=True, null=True)),
                ("peg", models.FloatField(blank=True, null=True)),
                ("ps", models.FloatField(blank=True, null=True)),
                ("pb", models.FloatField(blank=True, null=True)),
                ("price_cash", models.FloatField(blank=True, null=True)),
                ("price_fcf", models.FloatField(blank=True, null=True)),
                ("eps_growth_this_year", models.FloatField(blank=True, null=True)),
                ("eps_growth_next_year", models.FloatField(blank=True, null=True)),
                ("eps_growth_five_years", models.FloatField(blank=True, null=True)),
                ("eps_growth", models.FloatField(blank=True, null=True)),
                ("revenue_growth", models.FloatField(blank=True, null=True)),
                ("return_on_assets", models.FloatField(blank=True, null=True)),
                ("return_on_equity", models.FloatField(blank=True, null=True)),
                ("current_ratio", models.FloatField(blank=True, null=True)),
                ("quick_ratio", models.FloatField(blank=True, null=True)),
                ("debt_equity", models.FloatField(blank=True, null=True)),
                ("gross_margin", models.FloatField(blank=True, null=True)),
                ("operating_margin", models.FloatField(blank=True, null=True)),
                ("net_profit_margin", models.FloatField(blank=True, null=True)),
                ("payout_ratio", models.FloatField(blank=True, null=True)),
                ("institutional_ownership", models.FloatField(blank=True, null=True)),
                ("d1", models.FloatField(blank=True, null=True)),
                ("d5", models.FloatField(blank=True, null=True)),
                ("m1", models.FloatField(blank=True, null=True)),
                ("m3", models.FloatField(blank=True, null=True)),
                ("m6", models.FloatField(blank=True, null=True)),
                ("ytd", models.FloatField(blank=True, null=True)),
                ("y1", models.FloatField(blank=True, null=True)),
                ("y3", models.FloatField(blank=True, null=True)),
                ("y5", models.FloatField(blank=True, null=True)),
                ("y10", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
