from rest_framework.serializers import ModelSerializer, Serializer
from rest_framework import serializers
from .models import Ticker 


# class TickerResponseSerializer(Serializer):
#     name = serializers.CharField(max_length=120, required=False)
#     exchange = serializers.CharField(max_length=120, required=False)
#     sector = serializers.CharField(max_length=120, required=False)
#     industry = serializers.CharField(max_length=120, required=False)
#     country = serializers.CharField(max_length=120, required=False)
#     market_cap = serializers.FloatField(required=False)
#     dividend_yield = serializers.FloatField(required=False)
#     analyst_recom = serializers.CharField(max_length=120, required=False)
#     earning_date = serializers.CharField(max_length=120, required=False)
#     avg_volume = serializers.FloatField(required=False)
#     relative_volume = serializers.FloatField(required=False)
#     current_volume = serializers.FloatField(required=False)
#     price = serializers.FloatField(required=False)
#     ipo_date = serializers.CharField(max_length=120, required=False)
#     float = serializers.FloatField(required=False)
#     outstanding_shares = serializers.FloatField(required=False)
#     pe = serializers.FloatField(required=False)
#     forward_pe = serializers.FloatField(required=False)
#     peg = serializers.FloatField(required=False)
#     ps = serializers.FloatField(required=False)
#     pb = serializers.FloatField(required=False)
#     price_cash = serializers.FloatField(required=False)
#     price_fcf = serializers.FloatField(required=False)
#     eps_growth_this_year = serializers.FloatField(required=False)
#     eps_growth_next_year = serializers.FloatField(required=False)
#     eps_growth_five_years = serializers.FloatField(required=False)
#     eps_growth = serializers.FloatField(required=False)
#     revenue_growth = serializers.FloatField(required=False)
#     return_on_assets = serializers.FloatField(required=False)
#     return_on_equity = serializers.FloatField(required=False)
#     current_ratio = serializers.FloatField(required=False)
#     quick_ratio = serializers.FloatField(required=False)
#     debt_equity = serializers.FloatField(required=False)
#     gross_margin = serializers.FloatField(required=False)
#     operating_margin = serializers.FloatField(required=False)
#     net_profit_margin = serializers.FloatField(required=False)
#     payout_ratio = serializers.FloatField(required=False)
#     institutional_ownership = serializers.FloatField(required=False)
#     d1 = serializers.FloatField(required=False)
#     d5 = serializers.FloatField(required=False)
#     m1 = serializers.FloatField(required=False)
#     m3 = serializers.FloatField(required=False)
#     m6 = serializers.FloatField(required=False)
#     ytd = serializers.FloatField(required=False)
#     y1 = serializers.FloatField(required=False)
#     y3 = serializers.FloatField(required=False)
#     y5 = serializers.FloatField(required=False)
#     y10 = serializers.FloatField(required=False)
#     max_value = serializers.FloatField(required=False)


class TickerSerializer(Serializer):
    name = serializers.CharField(max_length=120, required=False)
    exchange = serializers.CharField(max_length=120, required=False)
    sector = serializers.CharField(max_length=120, required=False)
    industry = serializers.CharField(max_length=120, required=False)
    country = serializers.CharField(max_length=120, required=False)
    market_cap = serializers.CharField(max_length=120, required=False)
    dividend_yield = serializers.CharField(max_length=120, required=False)
    analyst_recom = serializers.CharField(max_length=120, required=False)
    earning_date = serializers.CharField(max_length=120, required=False)
    avg_volume = serializers.CharField(max_length=120, required=False)
    relative_volume = serializers.CharField(max_length=120, required=False)
    current_volume = serializers.CharField(max_length=120, required=False)
    price = serializers.CharField(max_length=120, required=False)
    ipo_date = serializers.CharField(max_length=120, required=False)
    float = serializers.CharField(max_length=120, required=False)
    outstanding_shares = serializers.CharField(max_length=120, required=False)
    pe = serializers.CharField(max_length=120, required=False)
    forward_pe = serializers.CharField(max_length=120, required=False)
    peg = serializers.CharField(max_length=120, required=False)
    ps = serializers.CharField(max_length=120, required=False)
    pb = serializers.CharField(max_length=120, required=False)
    price_cash = serializers.CharField(max_length=120, required=False)
    price_fcf = serializers.CharField(max_length=120, required=False)
    eps_growth_this_year = serializers.CharField(max_length=120, required=False)
    eps_growth_next_year = serializers.CharField(max_length=120, required=False)
    eps_growth_five_years = serializers.CharField(max_length=120, required=False)
    eps_growth = serializers.CharField(max_length=120, required=False)
    revenue_growth = serializers.CharField(max_length=120, required=False)
    return_on_assets = serializers.CharField(max_length=120, required=False)
    return_on_equity = serializers.CharField(max_length=120, required=False)
    current_ratio = serializers.CharField(max_length=120, required=False)
    quick_ratio = serializers.CharField(max_length=120, required=False)
    debt_equity = serializers.CharField(max_length=120, required=False)
    gross_margin = serializers.CharField(max_length=120, required=False)
    operating_margin = serializers.CharField(max_length=120, required=False)
    net_profit_margin = serializers.CharField(max_length=120, required=False)
    payout_ratio = serializers.CharField(max_length=120, required=False)
    institutional_ownership = serializers.CharField(max_length=120, required=False)
    d1 = serializers.CharField(max_length=120, required=False)
    d5 = serializers.CharField(max_length=120, required=False)
    m1 = serializers.CharField(max_length=120, required=False)
    m3 = serializers.CharField(max_length=120, required=False)
    m6 = serializers.CharField(max_length=120, required=False)
    ytd = serializers.CharField(max_length=120, required=False)
    y1 = serializers.CharField(max_length=120, required=False)
    y3 = serializers.CharField(max_length=120, required=False)
    y5 = serializers.CharField(max_length=120, required=False)
    y10 = serializers.CharField(max_length=120, required=False)
    max_value = serializers.CharField(max_length=120, required=False)


